### ISSUE TITLE
Retiring the five-level hierarchy: what is left, and why it is not just deletion

### ISSUE THREAD

**Issue by Codys-Wright** [FastTrackStudios/signal#11]
The domain is now one recursive node — `signal_proto::node::Node`, with a
resolver, stable UUIDs, styx and sqlite persistence, parameter ranges, and
gapless switching enforced by the type system. The worship guitar rig plays
through it end to end.

What is **not** done is retiring the model it replaces. This issue is what
that takes, and why it is not just deletion.

Branch: `domain-realign` (19 commits, local — not pushed).

## The blocker, stated plainly

The five repositories and ten entity types are not dead code. **They are the
working REAPER integration.** Deleting them is not finishing a migration, it
is removing a feature.

`ProfileOps::activate_patch` resolves through `resolve_service` (1,159 lines)
into a `ResolvedGraph` and hands that to a DAW applier. A node tree is not a
`ResolvedGraph` and must not be bent into one — `apply_graph` would report
success for a rig REAPER never received. So the node path stops short of the
DAW on purpose, and `NodeOps::activate_patch` emits `applied_to_daw: false`
and means it.

Everything below is blocked behind one thing: **an applier that speaks nodes.**

## 1. A DAW applier for node trees

The piece everything else waits on. Needs to accept
`signal_proto::node_resolve::Resolved` and build the REAPER-side rig from it,
the way `apply_graph` does from a `ResolvedGraph` today.

Cannot be verified by a test. Needs REAPER running against a real project,
and the result judged by ear. That is why it stopped here rather than being
guessed at.

## 2. Move the remaining call sites

Once (1) exists, three call sites move — one at a time, each small:

- `controller/src/ops/profiles.rs:188` — `activate_patch`
- `controller/src/variation.rs:251` — song scene switching
- `controller/src/lib.rs:339` — the public `resolve_target` passthrough

`signal_live::node_service::resolve_patch_target` already returns `Ok(None)`
for a target that is still one of the five level-specific variants, so both
paths run side by side while this happens.

## 3. Browser and UI

They consume `ResolvedGraph`. They move to `Resolved` after (2).

## 4. Then, and only then, the deletions

- `block_repo`, `module_repo`, `layer_repo`, `engine_repo`, `rig_repo`
- the ten entity types behind them (of 22 total)
- `resolve_service.rs` — 1,159 lines
- the five level-specific `PatchTarget` variants (`RigScene`, `EngineScene`,
  `LayerSnapshot`, `ModuleSnapshot`, `BlockSnapshot`), superseded by
  `PatchTarget::Node`
- `SceneSource::RigScene`, superseded by `SceneSource::Node`
- `impl_collection!` and the five Collection/Variant pairs in `signal-proto`

## Separately: two things worth doing on their own

**A units pass on the shipped rig.** `BlockParameter` now carries a
`ParameterRange` (min/max/taper/unit), and the audio bridge denormalizes
through it. The worship profile's own parameters do not have ranges yet, so
they still cross as bare normalized values. Giving the chain builder's blocks
real ranges — 80 Hz on a log range, −40 dB on a linear one — is a contained
job and makes every value in the UI printable.

**`catalog.json` wants to be a table.** It is one JSON blob loaded whole, and
`presets()` now parses the entire catalog on every performance-model change.
Fine at one entry, a stutter on a footswitch press at two thousand. The rig's
own config should stay styx; the capture library is the part that wants
sqlite.

## Not part of this

The pre-existing test failures are #8, not this. Measured against a clean
tree during this work: `signal-sampler`'s `document_mode` /
`annotation_parity` / `keyscape_rhodes`, `signal-proto`'s two `plugin_block`
tests, and `signal-live`'s `test_live_browser_index_load_time_smoke` all fail
identically without any of these changes.

## Three bugs this surfaced, already fixed on the branch

Recording them because each was silent and none had a test:

1. **The override system could not be saved at all.** `NodePathSegment` and
   `NodeOverrideOp` were tuple-variant enums, and facet-styx cannot
   round-trip one — it writes `@Engine"x"` and cannot read it back. Both
   halves. It worked in memory and would have failed the first time anyone
   wrote a rig to disk.
2. **`from_proto` dropped every parameter.** Block names, params, bypass and
   block type were all discarded, and a native block with no IR was skipped
   outright. The Amp EQ's five bands could not survive the trip, which is why
   the guitar rig never used that bridge.
3. **`BlockParameter` clamped 5500 Hz to 1.0.** `ParameterValue` is
   normalized and clamped to 0..=1, with nowhere to put a scale. Silent.

**Comment by Codys-Wright** [comment]
Merged to `main` — `2bc3f0d8..f5d3b51e`, 20 commits. The `domain-realign` branch is gone; everything above is on `main`.

One thing the merge turned up: **`main` was not compiling.** `guide-plugin` failed with `error[E0425]: cannot find type `NoteName`` — the break the nice-plug pull left behind. It is fixed in the first commit of this set, so the merge repairs it rather than just adding to it. That also means #8's failure counts predate the break and were measured against a tree that still built.

After the merge: native and wasm clean, 1822 tests run, 1800 passed, 21 failed + 1 timed out. Every one of those is in #8's set — verified against a clean tree during the work, not assumed.

**Comment by Codys-Wright** [comment]
Companion: #12 covers the realignment that is left *after* this one — three recursive models of the same idea (`Node`, `RigNode`/`Container`, `RigPreset`), what `Node` is missing that would let the keys rig use it, and the routing axis that is still name-addressed.

**Comment by Codys-Wright** [comment]
Item 1 is done, and it was narrower than this issue states. `5248b8a0`.

**The applier reads the resolved model in exactly one place.**
`apply_graph` calls `graph_state_chunks` to get an rfxchain document, and
that is all. The preload fast path, tail tracks, delayed mutes, track
creation and chunk splicing never looked at the graph. So that orchestration
is now one method both paths call, and the only thing that differs between a
graph and a node tree is which chunk extractor runs — the refactor removed
duplication rather than adding a second applier.

**What actually blocked it was a domain gap, not REAPER.**
`Snapshot::state_data` was `Option<Vec<u8>>`: arbitrary bytes, on a
block-level snapshot, with nothing saying which host could read them. For
this path those bytes are a whole `.rfxchain` document — not one block's
plugin state, which `HostedPluginRef::state_b64` already covers. A node had
nowhere to put it.

`BlockKind::HostChain { chain: HostChainRef }` is that home: the realization
for a rig **imported** rather than built. One leaf standing for a chain the
host saved, which is what it is from the domain's side — one opaque
processing unit. It carries the host's name, so `node_state_chunks` skips a
chain saved by something else and says why, instead of handing a foreign
document to REAPER and reporting success.

The document is stored base64 despite being text: facet-styx writes a
multi-line string as a heredoc it cannot read back (`unexpected token: got
unclosed object`), and the live rig keeps its library as styx, so a field
holding real newlines makes the library unloadable. Third limitation of that
format to shape a type in this work, after newtype tuple variants and
optional unit-tagged enums.

**Four tests cover the part this issue called untestable**, because it turned
out to be a pure function: a chain becomes its chunk byte for byte, a foreign
host's is skipped, a rig built rather than imported yields none, and chunks
follow chain order (the applier takes the first).

What still needs REAPER and an ear is whether the loaded chain *sounds*
right. The translation into it does not.

## Item 2, partly

`NodeOps::activate_patch` now applies through `DawPatchApplier::apply_node`,
so `applied_to_daw` means what it says. The trait's default refuses rather
than doing nothing quietly, so an applier that has not been taught nodes
reports false — still the truth.

The three call sites in the issue are unchanged: they are the *graph* path,
and they keep working. Moving them is now a question of when the node library
becomes the store those call sites read, not of whether an applier exists.

## Also

- The sampler renders a `HostChain` leaf as a pass-through with a warning —
  pass-through rather than silence on purpose, so an imported patch reaching
  the standalone rig lets the guitar through unprocessed.
- Every `eprintln!` in `reaper_applier.rs` and the controller's ops is now
  structured `tracing`, per the repo's logging rules. That file predated them.

## Still open here

Items 3 and 4 as written. Worth noting for item 4 that the deletions are
still guarded by the same thing: the five repos and ten entities are the
working REAPER integration until the node library is what those three call
sites read.
